parameters:
    # Paramètres pour l'API Gemini et Google Search
    gemini_api_key: '%env(GEMINI_API_KEY)%'
    google_search_api_key: '%env(GOOGLE_SEARCH_API_KEY)%'
    google_search_engine_id: '%env(GOOGLE_SEARCH_ENGINE_ID)%'
